spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/smart_platform?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ABcd@1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.jwt.secret=${APP_JWT_SECRET:ThisIsAVeryStrongSecretKeyForJwtAuthentication123456}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}

judge0.base-url=http://localhost:2358